/* ═══════════════════════════════════════════════════════════════
   ugcs.js  —  Unidades de Gestión Clínica del AGS Sur de Córdoba
   Plataforma Mentoría ACSA · Área Gestión Sanitaria Sur de Córdoba
   ═══════════════════════════════════════════════════════════════

   IDs asignados:
     HO_xxx  →  UGC Hospitalaria
     AP_xxx  →  UGC Atención Primaria
   ═══════════════════════════════════════════════════════════════ */

const UGCS = [

  /* ═══════════════════════════════════
     HOSPITALARIAS  (13)
  ════════════════════════════════════ */
  {
    "id":                   "HO_ANE",
    "denominacion":         "UGC Anestesiología, Cirugía General y Especialidades Quirúrgicas",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_COT",
    "denominacion":         "UGC Cirugía Ortopédica y Traumatología",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_UCI",
    "denominacion":         "UGC Cuidados Intensivos",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_FAR",
    "denominacion":         "UGC Farmacia",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_GIN",
    "denominacion":         "UGC Ginecología y Obstetricia",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_LAB",
    "denominacion":         "UGC Laboratorios",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla / CHARE Puente Genil",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_MED",
    "denominacion":         "UGC Medicina Interna y Especialidades Médicas",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_PED",
    "denominacion":         "UGC Pediatría",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_PRE",
    "denominacion":         "UGC Prevención, Promoción y Vigilancia de la Salud",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_REH",
    "denominacion":         "UGC Rehabilitación",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_PSI",
    "denominacion":         "UGC Salud Mental",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_PRO",
    "denominacion":         "UGC Protección de la Salud",
    "ubicacion":            "AGS Sur de Córdoba",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "HO_URG",
    "denominacion":         "UGC Urgencias Hospitalarias",
    "ubicacion":            "Hospital de Cabra / Hospital de Montilla / CHARE Puente Genil",
    "codigo_acsa":          "",
    "ambito":               "HOSP",
    "ambito_label":         "Hospitalaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },

  /* ═══════════════════════════════════
     ATENCIÓN PRIMARIA  (13)
  ════════════════════════════════════ */
  {
    "id":                   "AP_AGU",
    "denominacion":         "UGC Aguilar de la Frontera",
    "ubicacion":            "Aguilar de la Frontera",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_BAE",
    "denominacion":         "UGC Baena",
    "ubicacion":            "Baena",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_BEN",
    "denominacion":         "UGC Benamejí",
    "ubicacion":            "Benamejí",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_CAB",
    "denominacion":         "UGC Cabra",
    "ubicacion":            "Cabra",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_CAE",
    "denominacion":         "UGC Castro del Río – Espejo",
    "ubicacion":            "Castro del Río / Espejo",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_FER",
    "denominacion":         "UGC Fernán Núñez",
    "ubicacion":            "Fernán Núñez",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_RAM",
    "denominacion":         "UGC La Rambla",
    "ubicacion":            "La Rambla",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_LUC",
    "denominacion":         "UGC Lucena",
    "ubicacion":            "Lucena",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_MON",
    "denominacion":         "UGC Montilla",
    "ubicacion":            "Montilla",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_PRI",
    "denominacion":         "UGC Priego de Córdoba",
    "ubicacion":            "Priego de Córdoba",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_PUE",
    "denominacion":         "UGC Puente Genil",
    "ubicacion":            "Puente Genil",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_RUT",
    "denominacion":         "UGC Rute – Iznájar",
    "ubicacion":            "Rute / Iznájar",
    "codigo_acsa":          "",
    "ambito":               "AP",
    "ambito_label":         "Atención Primaria",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  },
  {
    "id":                   "AP_SUP",
    "denominacion":         "UGC Urgencias Córdoba Sur (SUAP)",
    "ubicacion":            "AGS Sur de Córdoba",
    "codigo_acsa":          "",
    "ambito":               "Urgencias",
    "ambito_label":         "Urgencias",
    "fase":                 "Sin solicitar",
    "estado_fase":          "",
    "fecha_inicio":         null,
    "fecha_prevista":       null,
    "fecha_fin":            null,
    "proyectos_anteriores": "",
    "direccion":            "",
    "telefono1":            "",
    "telefono2":            null,
    "correo":               "",
    "web":                  "",
    "observaciones":        ""
  }

];
