const UGCS = [
  {
    "id": "Ho_Ca_01",
    "denominacion": "Hospital de Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "2005/007",
    "ambito": "HOSP",
    "fase": "Solicitud de Certificación",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2012-04-19",
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "https://lc.cx/j0616L",
    "observaciones": "",
    "ambito_label": "Hospital"
  },
  {
    "id": "Ho_Ca_Ur_02",
    "denominacion": "UGC Urgencias Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "2017/118",
    "ambito": "Urgencias",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2023-07-03",
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Urgencias"
  },
  {
    "id": "Ho_Ca_La_03",
    "denominacion": "Laboratorio Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "2014/040",
    "ambito": "LAB",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2020-11-16",
    "proyectos_anteriores": "2020/009_R2 Abandonado",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Laboratorio"
  },
  {
    "id": "Ho_Ca_Rx_04",
    "denominacion": "UGC Radiodiagnóstico Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "2015/194",
    "ambito": "IMAG",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2022-01-29",
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Diagnóstico por Imagen"
  },
  {
    "id": "Ho_Ca_La_05",
    "denominacion": "UGC Anatomía Patológica Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_06",
    "denominacion": "UGC Anestesia y Reanimación Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_07",
    "denominacion": "UGC Cardiología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_08",
    "denominacion": "UGC Cirugía General y Digestiva Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_09",
    "denominacion": "UGC Cuidados Paliativos Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_10",
    "denominacion": "UGC Dermatología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_11",
    "denominacion": "UGC Digestivo Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_12",
    "denominacion": "UGC Ginecología y Obstetricia Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "2013/154",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2020-06-11",
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_13",
    "denominacion": "UGC Hematología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_14",
    "denominacion": "UGC Medicina Interna Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_15",
    "denominacion": "UGC Medicina Preventiva Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_16",
    "denominacion": "UGC Oftalmología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_17",
    "denominacion": "UGC Oncología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_18",
    "denominacion": "UGC Pediatría Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "2015/183",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2021-11-22",
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_19",
    "denominacion": "UGC Traumatología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Me_20",
    "denominacion": "UGC UCI Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_21",
    "denominacion": "UGC Urología Cabra",
    "ubicacion": "Hospital de Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_22",
    "denominacion": "UGC Maxilo-Facial",
    "ubicacion": "Interniveles",
    "codigo_acsa": "2017/002",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2023-07-18",
    "proyectos_anteriores": "",
    "direccion": "Av. de Góngora s/n - 14940",
    "telefono1": "957021300",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Ca_Qx_23",
    "denominacion": "UGC Otorrinolaringología",
    "ubicacion": "Interniveles",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "",
    "telefono1": null,
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Ur_01",
    "denominacion": "UGC Urgencias Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "Urgencias",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Urgencias"
  },
  {
    "id": "Ho_Mo_La_02",
    "denominacion": "Laboratorio Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "LAB",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Laboratorio"
  },
  {
    "id": "Ho_Mo_Rx_03",
    "denominacion": "UGC Radiodiagnóstico Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "IMAG",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Diagnóstico por Imagen"
  },
  {
    "id": "Ho_Mo_Md_04",
    "denominacion": "UGC Anatomía Patológica Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_05",
    "denominacion": "UGC Anestesia y Reanimación Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Md_06",
    "denominacion": "UGC Cardiología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_07",
    "denominacion": "UGC Cirugía General y Digestiva Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_08",
    "denominacion": "UGC Dermatología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Me_09",
    "denominacion": "UGC Digestivo Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_10",
    "denominacion": "UGC Genecología y Obstetricia Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Me_11",
    "denominacion": "UGC Hematología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Me_12",
    "denominacion": "UGC Medicina Interna Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_13",
    "denominacion": "UGC Oftalmología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_14",
    "denominacion": "UGC Otorrinolaringología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Me_15",
    "denominacion": "UGC Pediatría Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_16",
    "denominacion": "UGC Traumatología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Me_18",
    "denominacion": "UGC UCI Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Mo_Qx_18",
    "denominacion": "UGC Urología Montilla",
    "ubicacion": "Hospital de Montilla",
    "codigo_acsa": "",
    "ambito": "UGC_AH",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "A-309 Ctra. Montoro-Puente Genil Km. 65,350 - 14550",
    "telefono1": "957022600",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Atención Hospitalaria"
  },
  {
    "id": "Ho_Pg_Ur_01",
    "denominacion": "UGC Urgenias CHARE de Puente Genil",
    "ubicacion": "CHARE Puente Genil",
    "codigo_acsa": "2013/005",
    "ambito": "Urgencias",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2019-03-03",
    "proyectos_anteriores": "",
    "direccion": "Cl. Burgos s/n Políg. Indust. Las Acacias - 14500",
    "telefono1": "957615000",
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Urgencias"
  },
  {
    "id": "Ho_Pg_La_02",
    "denominacion": "Laboratorio Puente Genil",
    "ubicacion": "CHARE Puente Genil",
    "codigo_acsa": "",
    "ambito": "LAB",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "",
    "telefono1": null,
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Laboratorio"
  },
  {
    "id": "Ho_Pg_Rx_03",
    "denominacion": "UGC Radiodiagnóstico Puente Genil",
    "ubicacion": "CHARE Puente Genil",
    "codigo_acsa": "",
    "ambito": "IMAG",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "",
    "telefono1": null,
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "Diagnóstico por Imagen"
  },
  {
    "id": "Ap_01",
    "denominacion": "UGC Aguilar",
    "ubicacion": "Centro de Salud Aguilar",
    "codigo_acsa": "2016/087_R1",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2022-07-20",
    "proyectos_anteriores": "",
    "direccion": "Calle La Tercia 6 - 14920",
    "telefono1": "957699342",
    "telefono2": "957699344",
    "correo": "",
    "web": "https://lc.cx/g3nFvI",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_02",
    "denominacion": "UGC Baena",
    "ubicacion": "Centro de Salud Baena",
    "codigo_acsa": "2015/145",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2021-11-25",
    "proyectos_anteriores": "",
    "direccion": "Av. Salvador Muñoz 19 - 14850",
    "telefono1": "957699529",
    "telefono2": "957699525",
    "correo": "",
    "web": "https://lc.cx/mb-PhT",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_03",
    "denominacion": "UGC Benamejí",
    "ubicacion": "Centro de Salud Benamejí",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Recertificación",
    "estado_fase": "Empezado",
    "fecha_inicio": "2023-04-14",
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Prolongación José Marrón s/n - 14910",
    "telefono1": "957596728",
    "telefono2": null,
    "correo": "",
    "web": "https://lc.cx/_IThlx",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_04",
    "denominacion": "UGC Cabra",
    "ubicacion": "Centro de Salud Cabra",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. González Meneses s/n - 14940",
    "telefono1": "957506352",
    "telefono2": "957003610",
    "correo": "",
    "web": "https://lc.cx/D-DEQz",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_05",
    "denominacion": "UGC Castro del Río",
    "ubicacion": "Centro de Salud Castro del Río",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Mariano Fuentes 6 - 14840",
    "telefono1": "9579676",
    "telefono2": "957379675",
    "correo": "",
    "web": "https://lc.cx/6j7wwS",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_06",
    "denominacion": "UGC Fenán Núñez",
    "ubicacion": "Centro de Salud Fernán Núñez",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Doctor Emilio Luque s/n - 14520",
    "telefono1": "957379556",
    "telefono2": "957011172",
    "correo": "",
    "web": "https://lc.cx/jlSyVs",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_07",
    "denominacion": "UGC Iznájar",
    "ubicacion": "Centro de Salud Iznájar",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Julio Burrel 7, - 14970",
    "telefono1": "957506957",
    "telefono2": null,
    "correo": "",
    "web": "https://lc.cx/lPh-WN",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_08",
    "denominacion": "UGC La Rambla",
    "ubicacion": "Centro de Salud La Rambla",
    "codigo_acsa": "2016/086_R1",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2023-01-22",
    "proyectos_anteriores": "",
    "direccion": "Cl. Barrios 19 - 14540",
    "telefono1": "957699655",
    "telefono2": null,
    "correo": "",
    "web": "https://lc.cx/SSFxNJ",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_09",
    "denominacion": "UGC Lucena I",
    "ubicacion": "Centro de Salud Lucena I",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Paseo de Rojas s/n - 14900",
    "telefono1": "957596417",
    "telefono2": "957596418",
    "correo": "",
    "web": "https://lc.cx/wuD0Wv",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_10",
    "denominacion": "UGC Lucena II",
    "ubicacion": "Centro de Salud Lucena II",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Av. Santa Teresa 4 - 14900",
    "telefono1": "957596302",
    "telefono2": null,
    "correo": "",
    "web": "https://lc.cx/Fzpmbq",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_11",
    "denominacion": "UGC Montilla",
    "ubicacion": "Centro de Salud Montilla",
    "codigo_acsa": "2014/133",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2021-03-03",
    "proyectos_anteriores": "",
    "direccion": "Av. Andalucía 11 - 14550",
    "telefono1": "957699792",
    "telefono2": "957699757",
    "correo": "",
    "web": "https://lc.cx/2GwIMs",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_12",
    "denominacion": "UGC Priego de Córdoba",
    "ubicacion": "Centro de Salud Priego de Córdoba",
    "codigo_acsa": "2013/117",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2020-10-20",
    "proyectos_anteriores": "2022/035_01 Abandonado",
    "direccion": "Cl. Dr. Balbino Povedano Ruiz s/n - 14800",
    "telefono1": "957559518",
    "telefono2": "9579517",
    "correo": "",
    "web": "https://lc.cx/3YQyd6",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_13",
    "denominacion": "UGC Puente Genil I",
    "ubicacion": "Centro de Salud Puente Genil I",
    "codigo_acsa": "2017/030",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": "2023-09-18",
    "proyectos_anteriores": "",
    "direccion": "Cl. Doctor Fleming s/n -14500",
    "telefono1": "957618510",
    "telefono2": "957618511",
    "correo": "",
    "web": "https://lc.cx/3Gw9je",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_14",
    "denominacion": "UGC Puente Genil II",
    "ubicacion": "Centro de Salud Puente Genil II",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Miguel Qintero Merino s/n - 14500",
    "telefono1": "957615147",
    "telefono2": "957615149",
    "correo": "",
    "web": "https://lc.cx/OFr8eZ",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Ap_15",
    "denominacion": "UGC Rute",
    "ubicacion": "Centro de Salud Rute",
    "codigo_acsa": "",
    "ambito": "UGC_AP",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "Cl. Andalucía 1 - 14960",
    "telefono1": "957506928",
    "telefono2": null,
    "correo": "",
    "web": "https://lc.cx/b1r27D",
    "observaciones": "",
    "ambito_label": "Atención Primaria"
  },
  {
    "id": "Sm_01",
    "denominacion": "UGC Salud Mental Sur??",
    "ubicacion": "",
    "codigo_acsa": "",
    "ambito": "",
    "fase": "Sin solicitar",
    "estado_fase": "",
    "fecha_inicio": null,
    "fecha_prevista": null,
    "fecha_fin": null,
    "proyectos_anteriores": "",
    "direccion": "",
    "telefono1": null,
    "telefono2": null,
    "correo": "",
    "web": "",
    "observaciones": "",
    "ambito_label": "No definido"
  }
];